// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/account": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/products/:handle" | "/collections/:handle" | "/cart" | "/account";
  };
  "./routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/products.$handle.jsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "./routes/collections.$handle.jsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "./routes/cart.jsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "./routes/account.jsx": {
    id: "routes/account";
    page: "/account";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/_index": typeof import("./app/./routes/_index.jsx");
  "routes/products.$handle": typeof import("./app/./routes/products.$handle.jsx");
  "routes/collections.$handle": typeof import("./app/./routes/collections.$handle.jsx");
  "routes/cart": typeof import("./app/./routes/cart.jsx");
  "routes/account": typeof import("./app/./routes/account.jsx");
};